[deploy]
bucket = 'cloudproject-cfn-artifacts'
region = 'eu-west-2'
stack_name = 'CrdSrvBackendFlask'

[parameters]
EnvFrontendUrl = 'https://cloudproject.online'
EnvBackendUrl = 'https://api.cloudproject.online'